# Generated by Django 2.2 on 2020-08-29 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200829_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='option',
            field=models.TextField(max_length=2000, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(max_length=2000, verbose_name='Question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of answer')),
                ('choption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choption', to='webapp.Choice', verbose_name=' Chosen option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='webapp.Poll')),
            ],
        ),
    ]
